name = "FileIO"
uuid = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
version = "1.6.0"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
julia = "0.7, 1"

[extras]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
FilePathsBase = "48062228-2e41-5def-b9a4-89aafe57970f"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
PNGFiles = "f57f5aa1-a3ce-4bc8-8ab9-96f992907883"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ColorTypes", "FilePathsBase", "ImageIO", "PNGFiles", "Random", "Test"]
